### ISSUE TITLE
Adding CI using Github Actions?

### ISSUE THREAD

**Issue by lemastero** [jespercockx/agda2scheme#13]
Hello,
Thank you for creating this repository. I am studying this to learn how to write backend in Agda!

I play around with adding CI support to this on my fork here https://github.com/lemastero/agda2scheme/pull/1/, would it make sense to open such PR towards this repository?

**Comment by jespercockx** [comment]
Hi, I haven't looked at this repository in a while but any contributions to bring it up to date or make it easier to install and use would be very welcome!
